branches:
    - "2.5.x"
    - "2.6.x"
    - "2.7.x"
    - "2.8.x"
    - "2.9.x"
    - "2.10.x"
    - "2.11.x"
    - "2.12.x"
    - "2.13.x"
maintained_branches:
    - "2.12.x"
    - "2.13.x"
doc_dir: { "2.12.x": "docs/", "2.13.x": "docs/en/" }
current_branch: "2.12.x"
dev_branch: "2.13.x"
