branches:
    - "2.5.x"
    - "2.6.x"
    - "2.7.x"
    - "2.8.x"
    - "2.9.x"
    - "2.10.x"
    - "2.11.x"
    - "2.12.x"
maintained_branches:
    - "2.11.x"
    - "2.12.x"
doc_dir: "Resources/doc/"
current_branch: "2.11.x"
dev_branch: "2.12.x"
