branches:
    - "2.6.x"
    - "2.7.x"
    - "2.10.x"
    - "2.11.x"
    - "2.12.x"
    - "2.13.x"
    - "2.14.x"
    - "2.15.x"
    - "2.16.x"
    - "2.18.x"
    - "2.19.x"
    - "3.0.x"
    - "3.1.x"
    - "3.2.x"
    - "3.3.x"
    - "4.0.x"
maintained_branches:
    - "2.18.x"
    - "2.19.x"
    - "3.2.x"
    - "3.3.x"
    - "4.0.x"
doc_dir: "docs/en/"
current_branch: "3.2.x"
dev_branch: "3.3.x"
