branches:
    - "2.5.x"
    - "2.6.x"
    - "2.7.x"
    - "2.8.x"
    - "2.9.x"
    - "2.10.x"
    - "2.11.x"
    - "2.12.x"
    - "2.13.x"
    - "2.14.x"
    - "2.15.x"
    - "2.16.x"
    - "2.17.x"
maintained_branches:
    - "2.16.x"
    - "2.17.x"
doc_dir: "docs/en/"
current_branch: "2.16.x"
dev_branch: "2.17.x"
