
name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/coding-standards.yml
      - config/**
      - composer.*
      - phpcs.xml.dist
      - src/**
      - tests/**
  push:
    branches:
      - "*.x"
    paths:
      - .github/workflows/coding-standards.yml
      - config/**
      - composer.*
      - phpcs.xml.dist
      - src/**
      - tests/**

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@v12.2.0"
    with:
      composer-options: "--prefer-dist --prefer-stable"
